=== nifty-gui/nifty-gui/nifty-core/src/main/resources/nifty-1.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" targetNamespace="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="nifty" type="niftyType"></xs:element>

  <xs:element name="element" type="elementType"></xs:element>
  <xs:element name="layer" type="layerType" substitutionGroup="element"></xs:element>
  <xs:element name="panel" type="panelType" substitutionGroup="element"></xs:element>
  <xs:element name="image" type="imageType" substitutionGroup="element"></xs:element>
  <xs:element name="control" type="controlType" substitutionGroup="element"></xs:element>
  <xs:element name="text" type="textType" substitutionGroup="element"></xs:element>
  <xs:element name="popup" type="popupType" substitutionGroup="element"></xs:element>

  <xs:element name="effect" type="effectsType"></xs:element>
  <xs:element name="singleEffectbase" type="singleEffectTypeBase"></xs:element>
  <xs:element name="onStartScreen" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onEndScreen" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onHover" type="singleEffectTypeOnHover" substitutionGroup="singleEffectbase" />
  <xs:element name="onStartHover" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onEndHover" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onClick" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onFocus" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onLostFocus" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onGetFocus" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onActive" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onCustom" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onShow" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onHide" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onEnabled" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onDisabled" type="singleEffectType" substitutionGroup="singleEffectbase" />

  <xs:complexType name="elementType">
    <xs:sequence>
      <xs:element name="interact" type="interactType" maxOccurs="1" minOccurs="0" />
      <xs:element name="effect" type="effectsType" maxOccurs="1" minOccurs="0" />
      <xs:element ref="element" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="width" type="widthType" />
    <xs:attribute name="height" type="heightType" />
    <xs:attribute name="align" type="alignType" />
    <xs:attribute name="valign" type="valignType" />
    <xs:attribute name="childLayout" type="layoutType" />
    <xs:attribute name="childClip" type="xs:boolean" />
    <xs:attribute name="backgroundImage" type="xs:string" />
    <xs:attribute name="backgroundColor" type="colorType" />
    <xs:attribute name="visibleToMouse" type="xs:boolean" />
    <xs:attribute name="style" type="xs:string" />
    <xs:attribute name="renderOrder" type="xs:int" />
    <xs:anyAttribute processContents="skip" namespace="##any" />
  </xs:complexType>

  <xs:complexType name="layerType">
    <xs:complexContent>
      <xs:extension base="panelType" />
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="panelType">
    <xs:complexContent>
      <xs:extension base="elementType" />
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="imageType">
    <xs:complexContent>
      <xs:extension base="elementType">
        <xs:attribute type="xs:string" name="filename" use="optional" />
        <xs:attribute name="x" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="y" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="color" type="colorType" use="optional" ></xs:attribute>
        <xs:attribute name="filter" type="xs:boolean" use="optional"></xs:attribute>
        <xs:attribute name="imageMode" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="subImageSizeMode">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="scale"></xs:enumeration>
              <xs:enumeration value="resizeHint"></xs:enumeration>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="resizeHint" type="xs:string"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="colorType">
    <xs:restriction base="xs:string">
      <xs:pattern value="#[a-z,0-9]{8,8}"></xs:pattern>
      <xs:pattern value="#[a-z,0-9]{4,4}"></xs:pattern>
      <xs:minLength value="5"></xs:minLength>
      <xs:maxLength value="9"></xs:maxLength>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="layoutType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vertical"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="absolute"></xs:enumeration>
      <xs:enumeration value="horizontal"></xs:enumeration>
      <xs:enumeration value="overlay"></xs:enumeration>
      <xs:enumeration value="absolute-inside"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="directionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top"></xs:enumeration>
      <xs:enumeration value="bottom"></xs:enumeration>
      <xs:enumeration value="left"></xs:enumeration>
      <xs:enumeration value="right"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="textType">
    <xs:complexContent>
      <xs:extension base="elementType">
        <xs:attribute name="text" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="layout" type="layoutType" use="optional"></xs:attribute>
        <xs:attribute name="font" type="xs:string"></xs:attribute>
        <xs:attribute name="color" type="colorType"></xs:attribute>
        <xs:attribute name="textLineHeight" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="textMinHeight" type="xs:string" use="optional"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="alignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="left"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="right"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="widthType">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="heightType">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="valignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="bottom"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="controlDefinition">
    <xs:sequence>
      <xs:element ref="element" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"></xs:attribute>
    <xs:attribute name="controller" type="xs:string"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="controlType">
    <xs:complexContent>
      <xs:extension base="elementType">
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:anyAttribute processContents="skip" namespace="##any" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="useStylesType">
    <xs:attribute name="filename" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="useControlsType">
    <xs:attribute name="filename" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="registerSoundType">
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="filename" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="registerEffectType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="registerMusicType">
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="filename" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="registerMouseCursorType">
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="filename" type="xs:string" use="required" />
    <xs:attribute name="hotspotX" type="xs:string" use="optional" />
    <xs:attribute name="hotspotY" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="resourceBundleType">
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="filename" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="attributesType">
    <xs:attribute name="height" type="xs:string" />
    <xs:attribute name="width" type="xs:string" />
    <xs:attribute name="x" type="xs:string" />
    <xs:attribute name="y" type="xs:string" />
    <xs:attribute name="align" type="xs:string" />
    <xs:attribute name="valign" type="xs:string" />
    <xs:attribute name="paddingLeft" type="xs:string" />
    <xs:attribute name="paddingRight" type="xs:string" />
    <xs:attribute name="paddingTop" type="xs:string" />
    <xs:attribute name="paddingBottom" type="xs:string" />
    <xs:attribute name="padding" type="xs:string" />
    <xs:attribute name="marginLeft" type="xs:string" />
    <xs:attribute name="marginRight" type="xs:string" />
    <xs:attribute name="marginTop" type="xs:string" />
    <xs:attribute name="marginBottom" type="xs:string" />
    <xs:attribute name="margin" type="xs:string" />
    <xs:attribute name="childClip" type="xs:string" />
    <xs:attribute name="visible" type="xs:string" />
    <xs:attribute name="visibleToMouse" type="xs:string" />
    <xs:attribute name="childLayout" type="xs:string" />
    <xs:attribute name="focusable" type="xs:string" />
    <xs:attribute name="focusableInsertBeforeElementId" type="xs:string" />
    <xs:attribute name="backgroundImage" type="xs:string" />
    <xs:attribute name="backgroundColor" type="xs:string" />
    <xs:attribute name="color" type="xs:string" />
    <xs:attribute name="controller" type="xs:string" />
    <xs:attribute name="inputMapping" type="xs:string" />
    <xs:attribute name="textHAlign" type="xs:string" />
    <xs:attribute name="font" type="xs:string" />
    <xs:attribute name="filename" type="xs:string" />
    <xs:attribute name="wrap" type="xs:boolean" />
    <xs:attribute name="imageMode" type="xs:string" />
    <xs:attribute name="renderOrder" type="xs:int" />
  </xs:complexType>

  <xs:simpleType name="onClickType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:complexType name="interactType">
    <!-- these are mapped to the primary button -->
	<xs:attribute name="onClick" type="onClickType" />
    <xs:attribute name="onClickRepeat" type="onClickType" />
    <xs:attribute name="onClickMouseMove" type="onClickType" />
    <xs:attribute name="onRelease" type="onClickType" />

    <!-- called for primary button only (usually the left mouse button) -->
    <xs:attribute name="onPrimaryClick" type="onClickType" />
    <xs:attribute name="onPrimaryClickRepeat" type="onClickType" />
    <xs:attribute name="onPrimaryClickMouseMove" type="onClickType" />
    <xs:attribute name="onPrimaryRelease" type="onClickType" />

    <!-- called for secondary button only (usually the right mouse button) -->
    <xs:attribute name="onSecondaryClick" type="onClickType" />
    <xs:attribute name="onSecondaryClickRepeat" type="onClickType" />
    <xs:attribute name="onSecondaryClickMouseMove" type="onClickType" />
    <xs:attribute name="onSecondaryRelease" type="onClickType" />

    <!-- called for tertiary button only (usually the middle mouse button) -->
    <xs:attribute name="onTertiaryClick" type="onClickType" />
    <xs:attribute name="onTertiaryClickRepeat" type="onClickType" />
    <xs:attribute name="onTertiaryClickMouseMove" type="onClickType" />
    <xs:attribute name="onTertiaryRelease" type="onClickType" />

    <!-- methods called independent from the mouse buttons -->
    <xs:attribute name="onMouseOver" type="onClickType" />
    <xs:attribute name="onMouseWheel" type="onClickType" />
    <xs:attribute name="onClickAlternateKey" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="effectValueType">
    <xs:attribute name="time" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="offset" type="xs:string"/>
    <xs:attribute name="color" type="colorType"/>
  </xs:complexType>

  <xs:complexType name="singleEffectTypeBase">
    <xs:sequence>
      <xs:element name="value" type="effectValueType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="startDelay" type="xs:string" />
    <xs:attribute name="length" type="xs:string" />
    <xs:attribute name="oneShot" type="xs:boolean" />
    <xs:attribute name="timeType" type="xs:string" />
    <xs:attribute name="factor" type="xs:string" />
    <xs:attribute name="inherit" type="xs:boolean" />
    <xs:attribute name="post" type="xs:boolean" />
    <xs:attribute name="alternateEnable" type="xs:string" />
    <xs:attribute name="alternateDisable" type="xs:string" />
    <xs:attribute name="onStartEffect" type="onClickType" />
    <xs:attribute name="onEndEffect" type="onClickType" />
    <xs:anyAttribute namespace="##any" processContents="skip" />
  </xs:complexType>

  <xs:complexType name="singleEffectType">
    <xs:complexContent>
      <xs:extension base="singleEffectTypeBase"></xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="singleEffectTypeOnHover">
    <xs:complexContent>
      <xs:extension base="singleEffectType">
        <xs:sequence>
          <xs:element name="hover" type="onHoverType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="onHoverType">
    <xs:attribute name="hoverFalloffType" type="xs:string" />
    <xs:attribute name="hoverFalloffConstraint" type="xs:string" />
    <xs:attribute name="hoverWidth" type="xs:string" />
    <xs:attribute name="hoverHeight" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="singleEffectTypeHover">
    <xs:attribute name="width" type="widthType" />
    <xs:attribute name="height" type="heightType" />
  </xs:complexType>

  <xs:complexType name="effectsType">
    <xs:sequence>
      <xs:element ref="singleEffectbase" minOccurs="0" maxOccurs="unbounded" />
	  </xs:sequence>
    <xs:attribute name="overlay" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="styleType">
    <xs:sequence>
      <xs:element name="attributes" type="attributesType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="interact" type="interactType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="effect" type="effectsType" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="base" type="xs:string" />
  </xs:complexType>
 
  <xs:complexType name="popupType">
    <xs:complexContent>
      <xs:extension base="elementType" />
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="screenType">
    <xs:sequence>
      <xs:element name="layer" type="layerType" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"></xs:attribute>
    <xs:attribute name="controller" type="xs:string"></xs:attribute>
    <xs:attribute name="inputMapping" type="xs:string"></xs:attribute>
    <xs:attribute name="inputMappingPre" type="xs:boolean" use="optional"></xs:attribute>
    <xs:attribute name="defaultFocusElement" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="niftyType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="useStyles" type="useStylesType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="useControls" type="useControlsType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="registerSound" type="registerSoundType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="registerEffect" type="registerEffectType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="registerMusic" type="registerMusicType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="registerMouseCursor" type="registerMouseCursorType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="resourceBundle" type="resourceBundleType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="style" type="styleType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="controlDefinition" type="controlDefinition" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="screen" type="screenType" maxOccurs="unbounded" minOccurs="1" />
      <xs:element name="popup" type="popupType" maxOccurs="unbounded" minOccurs="0" />
    </xs:choice>
  </xs:complexType>
</xs:schema>

=== nifty-gui/nifty-gui/nifty-examples/src/main/resources/defaultcontrolsxml/15-tabs.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
  <useStyles filename="nifty-default-styles.xml"/>
  <useControls filename="nifty-default-controls.xml"/>
  <screen id="start">
    <layer id="layer" childLayout="center" backgroundColor="#003f">
      <panel id="tabs" childLayout="vertical" valign="center" align="center" width="50%" height="50%">
        <control id="edit_tabs" name="tabGroup">
          <control id="tab_1" name="tab" caption="Tab #1" childLayout="vertical" height="100%">
            <control align="center" valign="center" name="label" text="Content for Tab #1" width="100%" height="100%"
                />
          </control>
          <control id="tab_2" name="tab" caption="Tab #2" childLayout="vertical" height="100%">
            <control align="center" valign="center" name="label" text="Content for Tab #2" width="100%" height="100%"/>
          </control>
        </control>
      </panel>
    </layer>
  </screen>
</nifty>

=== nifty-gui/nifty-gui/nifty-examples/src/main/resources/allcontrols/allcontrols.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">

  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- load default styles and controls -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
<!--   <useStyles filename="nifty-default-styles.xml" />   -->
  <useStyles filename="nifty-default-styles.xml" />
  <useControls filename="nifty-default-controls.xml" />

  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- start screen -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <screen id="start" controller="de.lessvoid.nifty.examples.allcontrols.AllControlsDemoStartScreen">
    <layer id="layer" childLayout="center">
      <effect>
        <onActive name="gradient">
          <value offset="0%" color="#2220" />
          <value offset="100%" color="#555f" />
        </onActive>
      </effect>
      <panel id="dialog" style="nifty-panel" childLayout="center" width="50%" height="80%" align="center" valign="center" visibleToMouse="true">
        <effect>
          <onStartScreen name="move" timeType="exp" factor="3.5" direction="top" mode="in" length="500" inherit="true"/>
          <onEndScreen name="move" timeType="exp" factor="3.5" direction="bottom" mode="out" length="500" inherit="true"/>
        </effect>
        <panel childLayout="vertical" align="center" valign="center">
          <panel id="namePanel" childLayout="horizontal">
            <text id="labelName" text="Textfield: " width="100px" align="left" textVAlign="center" textHAlign="left" />
            <control id="name" name="textfield" text="Text Input" />
          </panel>
          <panel childLayout="horizontal" height="10px" />
          <panel childLayout="horizontal">
            <text text="Checkbox: " width="100px" align="left" textVAlign="center" textHAlign="left" />
            <control id="checkbox" name="checkbox" checked="false" />
          </panel>
          <panel childLayout="horizontal" height="10px" />
          <panel childLayout="horizontal">
            <text text="DropDown: " width="100px" align="left" textVAlign="center" textHAlign="left" />
            <control id="dropDown" name="dropDownControl" />
          </panel>
          <panel childLayout="horizontal" height="10px" />
          <panel childLayout="horizontal">
            <text text="Scrollbar H.: " width="100px" align="left" textVAlign="center" textHAlign="left" />
            <control name="horizontalScrollbar" worldMaxValue="10.0" />
          </panel>
          <panel childLayout="horizontal" height="10px" />
          <panel childLayout="horizontal">
            <text text="Scrollbar V.: " width="100px" align="left" textVAlign="center" textHAlign="left" />
            <control name="verticalScrollbar" height="100px" worldMaxValue="5.0" />
          </panel>
          <panel childLayout="horizontal" height="10px" />
          <panel childLayout="horizontal">
            <text text="Listbox: " width="100px" align="left" textVAlign="center" textHAlign="left" />
            <control id="listBox" name="listBox" horizontal="false" width="*" height="100px">
              <panel id="listBoxData" width="100%" childLayout="vertical" visibleToMouse="true" />
            </control>
          </panel>
          <panel childLayout="horizontal" height="10px" />
          <panel childLayout="horizontal">
            <text text="Scrollpanel: " width="100px" align="left" textVAlign="center" textHAlign="left" />
            <control name="scrollPanel" width="*" height="120px">
              <panel width="544px" height="158px" childLayout="center">
                <image filename="intro-logo.png" />
              </panel>
            </control>
          </panel>
          <panel childLayout="horizontal" height="*" />
          <panel childLayout="center" width="100%" height="50px">
            <control id="backButton" name="button" label="Back" align="center" valign="center" />
          </panel>
        </panel>
      </panel>
    </layer>
  </screen>
</nifty>

=== nifty-gui/nifty-gui/nifty-examples/src/main/resources/defaultcontrolsxml/13-textfield.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
  <useStyles filename="nifty-default-styles.xml"/>
  <useControls filename="nifty-default-controls.xml"/>

  <screen id="start">
    <layer childLayout="center">
      <panel width="25%" height="25%" align="center" valign="center" childLayout="vertical" backgroundColor="#55a5"
             padding="10">
        <control name="textfield"/>
        <control name="textfield" passwordChar="*"/>
        <control name="textfield" maxLength="10"/>
        <control name="textfield" filter="letters"/>
      </panel>
    </layer>
  </screen>
</nifty>

=== nifty-gui/nifty-gui/nifty-examples/src/main/resources/test/test-popup.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
  <useStyles filename="nifty-default-styles.xml" />
  <useControls filename="nifty-default-controls.xml" />

  <screen id="start" controller="de.lessvoid.nifty.examples.test.TestScreen">
    <layer id="stuff" childLayout="horizontal">
      <panel width="50%" height="50%w" valign="bottom" backgroundColor="#f0ff" visibleToMouse="true">
        <interact onClick="popup()"/>
      </panel>
    </layer>
  </screen>

  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <!-- sure to exit popup -->
  <!-- +++++++++++++++++++++++++++++++++++++++ -->
  <popup id="popupExit" childLayout="center" backgroundColor="#0001">
    <panel style="nifty-panel" childLayout="center" padding="18px,28px,40px,16px" width="30%" height="20%" align="center" valign="center">
      <panel childLayout="vertical" align="center" valign="center">
        <panel childLayout="center" height="70%" width="100%">
          <text text="Really want to Exit?" style="base-font" align="center" valign="center" color="#000f"/>
        </panel>
        <panel childLayout="horizontal" align="center" height="30%">
          <panel childLayout="center" width="50%">
            <control id="yesButton" name="button" label="Yes" width="100px" align="center">
              <interact onClick="popupExit(yes)" /> 
            </control>
          </panel>
          <panel childLayout="center" width="50%">
            <control id="noButton" name="button" label="No" width="100px" align="center">
              <interact onClick="popupExit(no)" /> 
            </control>
          </panel>
        </panel>
      </panel>
    </panel>
  </popup>
</nifty>

=== nifty-gui/nifty-gui/nifty-examples/src/main/resources/messagebox/messagebox.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
  <useStyles filename="nifty-default-styles.xml" />
  <useControls filename="nifty-default-controls.xml" />

  <screen id="start" controller="de.lessvoid.nifty.examples.messagebox.MessageBoxStartScreen">
    <layer id="layer" childLayout="vertical">
      <panel width="100%" height="50%" childLayout="center">
        <control id="messagebox" name="nifty-messagebox" messageBoxType="ERROR"
                 message="Hello! This is a message box! Fear it!" buttonCaptions="Yes,No,Maybe,Go away" />
      </panel>
      <panel width="100%" height="50" childLayout="horizontal">
        <panel childLayout="center">
          <control id="setInfo" name="button" label="As Information" align="center" valign="center">
            <interact onClick="changeMessageBoxType(INFO)" />
          </control>
        </panel>
        <panel childLayout="center">
          <control id="setWarn" name="button" label="As Warning" align="center" valign="center">
            <interact onClick="changeMessageBoxType(WARNING)" />
          </control>
        </panel>
        <panel childLayout="center">
          <control id="setError" name="button" label="As Error" align="center" valign="center">
            <interact onClick="changeMessageBoxType(ERROR)" />
          </control>
        </panel>
      </panel>
    </layer>
  </screen>
</nifty>
